include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gen.dart'
    - 'build/**'

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    unused_local_variable: warning
    missing_return: error
    dead_code: info

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    always_declare_return_types: true
    always_specify_types: true
    avoid_print: true
    avoid_redundant_argument_values: true
    use_key_in_widget_constructors: true
    require_trailing_commas: true
    prefer_single_quotes: true
    unnecessary_this: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    avoid_classes_with_only_static_members: true
    prefer_const_literals_to_create_immutables: true
    avoid_returning_null_for_future: true
    avoid_types_as_parameter_names: true
    annotate_overrides: true
    camel_case_types: true
    constant_identifier_names: true
    file_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    null_check_on_nullable_type_parameter: true
    prefer_expression_function_bodies: true
    prefer_typing_uninitialized_variables: true
    slash_for_doc_comments: true
    type_annotate_public_apis: true
    unnecessary_new: true
